POST http://localhost:3000/clientes
Content-Type: application/json
Authorization: 796551c9e48fae44d669ca5e55d05fd3

{
    "nome": "Cliente",
    "email": "cliente2@gmail.com",
    "cpfoucnpj": "99988877744",
    "telefone": "83999998888",
    "enderecos": [
        {
            "cep": "00000000",
            "rua": "Rua dois",
            "numero": "2534",
            "complemento": "APTO",
            "bairro": "Logo ali",
            "cidade": "SAnta Luzia",
            "uf": "RO"
        },
        {
            "cep": "58666666",
            "rua": "Rua",
            "numero": "845",
            "complemento": "APTO APTO APTO",
            "bairro": "São José",
            "cidade": "Patos",
            "uf": "RJ"
        }
    ]
}

###
GET http://localhost:3000/clientes/4
Authorization: 886258c408970a7dfd7bd775c0a21873

###
GET http://localhost:3000/clientes
Authorization: 79d07512d8676fffa244a14ffb15a05e

###
PUT http://localhost:3000/clientes/4
Content-Type: application/json
Authorization: 6bb2feff8411e8356d11b71c9f226eb8

{
  "nome": "Cliente 3 da Silva",
  "email": "clientedasilva33333@gmail.com",
  "cpfoucnpj": "3311122233344",
  "telefone": "83333",
  "enderecos": [
    {
      "id": "3",
      "idCliente": "4",
      "cep": "3333000",
      "rua": "Rua dois A",
      "complemento": "CASA",
      "numero": "2",
      "bairro": "Logo ali assim",
      "cidade": "SAnta Luzia dos grudes",
      "uf": "SP"
    },
    {
      "id": "4",
      "idCliente": "4",
      "cep": "333366666",
      "rua": "Rua",
      "complemento": " 33333 APTO APTO APTO",
      "numero": "845",
      "bairro": "São José",
      "cidade": "Patos",
      "uf": "RJ"
    }
  ]
}