POST http://localhost:3000/clientes
Content-Type: application/json
Authorization: 4d3b89a7a05cacf2d13a70ebb47f644d

{
    "nome": "Fulano de tal",
    "email": "fulano@gmail.com",
    "cpfoucnpj": "12345678901",
    "telefone": "83999998888",
    "enderecos": [
        {
            "cep": "25500456",
            "rua": "Rua torta",
            "numero": "25",
            "complemento": "Casa 2 - Fundos",
            "bairro": "Lugar nenhum",
            "cidade": "Imaginária",
            "uf": "PB"
        },
        {
            "cep": "58600000",
            "rua": "Rua torta das portas",
            "numero": "8787",
            "complemento": "APTO",
            "bairro": "Do Zé",
            "cidade": "Eita Danado",
            "uf": "RR"
        }
    ]
}

###
DELETE http://localhost:3000/logout
Authorization: 2ecb16f8a9b66c28c410bbdc30cfeebd 

###
GET http://localhost:3000/usuarios/8
Authorization: 9c34949c2570a41c0db3f64f49e20094

###
POST http://localhost:3000/usuarios/
Content-Type: application/json
Authorization: 96ef38c321487ca1d600f6a106333b87

{
    "nome": "João",
    "email": "joao@gmail.com",
    "senha": "654321",
    "idPerfil": 1
}

###
PUT http://localhost:3000/usuariosatualizar/8
Content-Type: application/json
Authorization: dd59489128a34b98ca66a6774267a016

{
  "nome": "Maria de Souza",
  "email": "mariadesouza@gmail.com",
  "idPerfil": 3
}