POST http://localhost:3000/servicos
Content-Type: application/json
Authorization: b16f8e6aa3576998f48177bc5123fd7a

{
    "descricao": "Serviõ 2 m²",
    "valor": 600.0
}

###
GET http://localhost:3000/servicos/4
Authorization: 886258c408970a7dfd7bd775c0a21873

###
GET http://localhost:3000/servicos
Authorization: 79d07512d8676fffa244a14ffb15a05e

###
PUT http://localhost:3000/servicos/4
Content-Type: application/json
Authorization: 6bb2feff8411e8356d11b71c9f226eb8

{
    "descricao": "Pintura interior m²",
    "valor": 100.0,
}
