POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "fulano@gmail.com",
    "senha": "123456"
}

###
DELETE http://localhost:3000/logout
Authorization: 2ecb16f8a9b66c28c410bbdc30cfeebd 

###
GET http://localhost:3000/usuarios/3
Authorization: c317a34b2fec8f9b4ee27a2e5717e89b

###
POST http://localhost:3000/usuarios/
Content-Type: application/json
Authorization: c317a34b2fec8f9b4ee27a2e5717e89b

{
    "nome": "Luan",
    "email": "luan@gmail.com",
    "senha": "123456",
    "idPerfil": 3
}

###
PUT http://localhost:3000/usuariosatualizar/5
Content-Type: application/json
Authorization: c317a34b2fec8f9b4ee27a2e5717e89b

{
  "nome": "Maria de Souza",
  "email": "mariadesouza@gmail.com",
  "idPerfil": 3
}